<a href="https://colab.research.google.com/github/marioarsw/AnaliticaDescriptiva/blob/main/practicas/practica4_267370.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Maestría en Inteligencia Artificial y Analítica de Datos


*   Curso: Programación para Analítica Descriptiva y Predictiva
*   Semestre: Enero-Junio
*   Profesor: Dr. Vicente García Jiménez



## Práctica 4: Matrices con NumPy

## Mario Amador - 267370.

Crea dos matrices de 3x3 con números aleatorios entre 1 y 10. Realiza las siguientes operaciones:

1. Suma ambas matrices.
2. Resta la segunda matriz de la primera.
3. Multiplica la primera matriz por 2.
4. Realiza una multiplicación matricial entre las dos matrices.

Imporación de librerías.

In [1]:
import numpy as np

Crea dos matrices de 3x3 con números aleatorios entre 1 y 10.

In [2]:
A = np.random.randint(1, 11, size=(3, 3))
B = np.random.randint(1, 11, size=(3, 3))

A, B

(array([[ 7,  6,  8],
        [ 3,  1, 10],
        [ 1,  3,  7]]),
 array([[10, 10,  4],
        [ 4,  3,  5],
        [ 2,  1,  9]]))

1. Suma ambas matrices

In [3]:
A + B

array([[17, 16, 12],
       [ 7,  4, 15],
       [ 3,  4, 16]])

2. Resta la segunda matriz de la primera.

In [5]:
A - B

array([[-3, -4,  4],
       [-1, -2,  5],
       [-1,  2, -2]])

3. Multiplica la primera matriz por 2.

In [6]:
A * 2

array([[14, 12, 16],
       [ 6,  2, 20],
       [ 2,  6, 14]])

4. Realiza una multiplicación matricial entre las dos matrices.

In [7]:
A * B

array([[70, 60, 32],
       [12,  3, 50],
       [ 2,  3, 63]])