<a href="https://colab.research.google.com/github/marioarsw/AnaliticaDescriptiva/blob/main/talleres/6_ejercicios_numpy_pandas_sesion02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Creación de arreglos:**

Ejercicio: Crea un arreglo de 10 elementos con valores enteros aleatorios entre 0 y 50

In [ ]:
import numpy as np
arr = np.random.randint(0, 51, 10)
print(arr)


[ 3 33 21 33  7  9  4 21 20  3]


**Operaciones element-wise:**

Ejercicio: Realiza las siguientes operaciones en el arreglo generado en el ejercicio anterior:

1.   Multiplica cada elemento por 2.
2.   Suma 5 a cada elemento.
3. Divide cada elemento por 3.


In [ ]:
arr = np.random.randint(0, 51, 10)
print("Original:", arr)
print("Multiplicado por 2:", arr * 2)
print("Suma de 5:", arr + 5)
print("División por 3:", arr / 3)


Original: [50 20 30 22  6 16 44  8 21 41]
Multiplicado por 2: [100  40  60  44  12  32  88  16  42  82]
Suma de 5: [55 25 35 27 11 21 49 13 26 46]
División por 3: [16.66666667  6.66666667 10.          7.33333333  2.          5.33333333
 14.66666667  2.66666667  7.         13.66666667]


**Índices y segmentación:**

Ejercicio: Crea un arreglo de 20 números enteros del 1 al 100. Luego, extrae:
1. Los primeros 5 elementos.
2. Los últimos 5 elementos.
3. Los elementos en posiciones pares.

In [ ]:
arr = np.random.randint(1, 101, 20)
print("Original:", arr)
print("Primeros 5 elementos:", arr[:5])
print("Últimos 5 elementos:", arr[-5:])
print("Elementos en posiciones pares:", arr[::2])


Original: [ 52  54  40  33  61  25  72  45  56  23  80   7  36  47  99   2  81  13
  71 100]
Primeros 5 elementos: [52 54 40 33 61]
Últimos 5 elementos: [  2  81  13  71 100]
Elementos en posiciones pares: [52 40 61 72 56 80 36 99 81 71]


**Cálculo de estadísticas:**
Ejercicio: Crea un arreglo de 50 números aleatorios entre 0 y 100. Luego, calcula:
.
1. La media.
2. La mediana.
3. La desviación estándar.

In [ ]:
arr = np.random.randint(0, 101, 50)
print("Media:", np.mean(arr))
print("Mediana:", np.median(arr))
print("Desviación estándar:", np.std(arr))


Media: 52.6
Mediana: 57.0
Desviación estándar: 27.453232960800808


**Operaciones con matrices:**

Ejercicio: Crea dos matrices de 3x3 con números aleatorios. Luego:
1. Suma las dos matrices.
2. Realiza una multiplicación matricial.

In [ ]:
A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))
print("Matriz A:", A)
print("Matriz B:", B)
print("Suma de matrices:", A + B)
print("Multiplicación matricial:", np.dot(A, B))


Matriz A: [[8 4 4]
 [3 5 3]
 [4 6 9]]
Matriz B: [[6 2 2]
 [9 5 1]
 [6 5 3]]
Suma de matrices: [[14  6  6]
 [12 10  4]
 [10 11 12]]
Multiplicación matricial: [[108  56  32]
 [ 81  46  20]
 [132  83  41]]


**Máscaras booleanas:**

Ejercicio: Crea un arreglo de 10 números aleatorios entre 1 y 100. Luego, usa una máscara booleana para seleccionar los elementos mayores que 50.

In [ ]:
arr = np.random.randint(1, 101, 10)
print("Original:", arr)
mask = arr > 50
print("Elementos mayores que 50:", arr[mask])

Original: [76 28  8 39 10 57 26 59 20 33]
Elementos mayores que 50: [76 57 59]


 **Reshape y redimensionamiento:**

Ejercicio: Crea un arreglo unidimensional con 12 elementos. Luego, redimensionalo a una matriz de 3x4.

In [ ]:
arr = np.arange(1, 13)
print("Arreglo original:", arr)
arr_reshape = arr.reshape(3, 4)
print("Matriz 3x4:", arr_reshape)


Arreglo original: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Matriz 3x4: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**Concatenación y apilamiento de arreglos:**

Ejercicio: Crea dos arreglos unidimensionales de 5 elementos. Concátalos y apílalos verticalmente.

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
print("Concatenación horizontal:", np.concatenate((arr1, arr2)))
print("Apilamiento vertical:", np.vstack((arr1, arr2)))


Concatenación horizontal: [ 1  2  3  4  5  6  7  8  9 10]
Apilamiento vertical: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


**Manejo de valores NaN (Not a Number):**

Ejercicio: Crea un arreglo de 5 elementos con valores NaN y reemplázalos por el valor 0

In [ ]:
arr = np.array([1, 2, np.nan, 4, np.nan])
print("Original con NaN:", arr)
arr[np.isnan(arr)] = 0
print("Sin NaN:", arr)


Original con NaN: [ 1.  2. nan  4. nan]
Sin NaN: [1. 2. 0. 4. 0.]


**Generación de números aleatorios más compleja:**

Ejercicio: Crea una matriz 3x3 con números aleatorios provenientes de una distribución normal con media 0 y desviación estándar 1.

In [ ]:
arr = np.random.normal(0, 1, (3, 3))
print("Matriz con distribución normal:", arr)


Matriz con distribución normal: [[-0.15133665  0.35187185  1.57973182]
 [ 0.6117532  -1.50716077 -0.68869558]
 [ 1.40235171 -1.34922262 -1.36960932]]


**Funciones universales (ufuncs):**

Ejercicio: Aplica funciones matemáticas a un arreglo, como el seno, coseno o logaritmo natural

In [ ]:
arr = np.array([0, np.pi/2, np.pi])
print("Seno de los elementos:", np.sin(arr))
print("Coseno de los elementos:", np.cos(arr))
print("Logaritmo natural de los elementos:", np.log(arr))


Seno de los elementos: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Coseno de los elementos: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Logaritmo natural de los elementos: [      -inf 0.45158271 1.14472989]


<ipython-input-11-96fa36a54ab8>:4: RuntimeWarning: divide by zero encountered in log
  print("Logaritmo natural de los elementos:", np.log(arr))


**Suma acumulativa y producto acumulativo:**

Ejercicio: Crea un arreglo y calcula la suma y el producto acumulativo de los elementos.

In [ ]:
arr = np.array([1, 2, 3, 4])
print("Suma acumulativa:", np.cumsum(arr))
print("Producto acumulativo:", np.cumprod(arr))


Suma acumulativa: [ 1  3  6 10]
Producto acumulativo: [ 1  2  6 24]


Reducción de dimensiones (suma, media, etc. en matrices):

Ejercicio: Crea una matriz 3x3 y calcula la suma de los elementos por columna y por fila

In [ ]:
arr = np.random.randint(1, 10, (3, 3))
print("Matriz original:", arr)
print("Suma por columna:", np.sum(arr, axis=0))
print("Suma por fila:", np.sum(arr, axis=1))


Matriz original: [[1 4 2]
 [2 6 6]
 [3 7 5]]
Suma por columna: [ 6 17 13]
Suma por fila: [ 7 14 15]


** Cálculo de la inversa de una matriz:**

Ejercicio: Crea una matriz de 2x2 invertible y calcula su inversa

In [ ]:
A = np.array([[1, 2], [3, 4]])
print("Matriz A:", A)
A_inv = np.linalg.inv(A)
print("Inversa de A:", A_inv)


Matriz A: [[1 2]
 [3 4]]
Inversa de A: [[-2.   1. ]
 [ 1.5 -0.5]]


**Transposición de matrices:**

Ejercicio: Crea una matriz 2x3 y luego realiza la transposición de la misma.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Matriz original:", arr)
print("Matriz transpuesta:", arr.T)


Matriz original: [[1 2 3]
 [4 5 6]]
Matriz transpuesta: [[1 4]
 [2 5]
 [3 6]]


**Indexación avanzada (usando np.ix_):**

Ejercicio: Usa la función np.ix_ para realizar una indexación avanzada y extraer submatrices.

In [ ]:
arr = np.random.randint(1, 10, (4, 4))
print("Matriz original:", arr)
row_indices = np.array([0, 2])
col_indices = np.array([1, 3])
print("Submatriz usando np.ix_:", arr[np.ix_(row_indices, col_indices)])


Matriz original: [[8 3 7 4]
 [6 2 5 6]
 [5 6 4 4]
 [3 3 9 3]]
Submatriz usando np.ix_: [[3 4]
 [6 4]]


Resolución de sistemas de ecuaciones lineales:

Ejercicio: Usa np.linalg.solve para resolver un sistema de ecuaciones lineales

In [ ]:
# Resolver el sistema Ax = b
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)
print("Solución del sistema:", x)


Solución del sistema: [2. 3.]


**Uso de np.unique:**

Ejercicio: Crea un arreglo con algunos elementos repetidos y usa np.unique para obtener los elementos únicos.

In [ ]:
arr = np.array([1, 2, 2, 3, 4, 4, 5])
print("Elementos únicos:", np.unique(arr))


Elementos únicos: [1 2 3 4 5]
